name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push to ECR and update App Runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Extract backend ECR repository name and URI
        id: ecr-backend
        run: |
          echo "::set-output name=uri::${{ secrets.BACKEND_ECR_REPOSITORY_URI }}"
      - name: Extract frontend ECR repository name and URI
        id: ecr-frontend
        run: |
          echo "::set-output name=uri::${{ secrets.FRONTEND_ECR_REPOSITORY_URI }}"
      - name: Build and Push Docker Image to ECR (Backend)
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ steps.ecr-backend.outputs.uri }}:latest .
          docker push ${{ steps.ecr-backend.outputs.uri }}:latest
      - name: Build and Push Docker Image to ECR (Frontend)
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ steps.ecr-frontend.outputs.uri }}:latest .
          docker push ${{ steps.ecr-frontend.outputs.uri }}:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update App Runner Service (Backend)
        run: |
          aws apprunner update-service \
            --service-arn ${{ secrets.APP_RUNNER_BACKEND_ARN }} \
            --source-configuration ImageRepository={ImageIdentifier=${{ secrets.BACKEND_ECR_REPOSITORY_URI }}:latest,ImageRepositoryType=ECR}
      - name: Update App Runner Service (Frontend)
        run: |
          aws apprunner update-service \
            --service-arn ${{ secrets.APP_RUNNER_FRONTEND_ARN }} \
            --source-configuration ImageRepository={ImageIdentifier=${{ secrets.FRONTEND_ECR_REPOSITORY_URI }}:latest,ImageRepositoryType=ECR}
